# [作業目標]

1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```

2. 請對一個 5x5 的隨機矩陣作正規化的操作。

3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


# 作業 

### 1. [簡答題] 請問下列這三種方法有什麼不同？

```
print(a.sum()) 
print(np.sum(a))
print(sum(a)) 
```



In [ ]:
"a.sum()和np.sum(a)得出來的結果是一樣的，但在多維陣列的情況底下，sum(a)得到的結果會是以axis=0方向加總的結果"

'\nYour Code\n'

### 2. 請對一個 5x5 的隨機矩陣作正規化的操作。


In [2]:
# 記得先 Import 正確的套件
import numpy as np

In [5]:
A = np.random.random((5, 5))

A = (A - A.min()) / (A.max() - A.min())
print(A)

[[0.353377   0.20324139 0.67941137 0.13303391 0.26773697]
 [0.76605125 0.9988311  0.89774727 0.84402661 0.65239027]
 [0.77234868 0.79040504 0.94906759 0.16826035 0.85504895]
 [0.12989479 0.09817319 0.30631856 1.         0.64828844]
 [0.74191445 0.92548918 0.         0.06143025 0.73406954]]


### 3. 請建立一個長度等於 10 的正整數向量，並且將其中的最大值改成 -1。


In [11]:
#Create an array with length of 10
Array = np.random.random(10)

3

In [14]:
# Locate and make the biggest number -1 
Array[np.argmax(Array)] = -1

In [16]:
print(Array)

[ 0.27924342  0.0840944   0.81446642 -1.          0.32307227  0.67917987
  0.87183005  0.05411046  0.04760806  0.07869879]
